//! The two copies of the vocabulary, and the one thing that keeps them one file.
//!
//! WHAT BREAKS WITHOUT THIS FILE. The vocabulary ships TWICE at the repository
//! root: `ns.ttl`, which is what a human opens, and `ns`, which is what the
//! namespace IRI `https://semantic.ds-labs.org/vocab/honeycomb#` will resolve to
//! once that host is standing — the sibling ds-odrl-compliance-rdf carries the
//! same pair for the same reason. Nothing in this workspace links either of
//! them, so nothing notices when an edit lands in one and not the other.
//!
//! And the failure that follows is the quietest one available. A reader who
//! opens the file in the repository and a tool that dereferences the namespace
//! would be reading two different vocabularies, both well-formed, both parsing,
//! with no error anywhere and nothing in either file admitting the other exists.
//! `honeycomb-core/tests/vocabulary.rs` checks `ns.ttl` alone, because that is
//! the copy this crate is the owner of; this file is what stops the published
//! copy drifting away from the one those checks ran against.

const NS_TTL: &str = "ns.ttl";
const NS_BARE: &str = "ns";

fn read(name: &str) -> Vec<u8> {
    let path = format!("{}/../{}", env!("CARGO_MANIFEST_DIR"), name);
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "{name} could not be read at {path}: {e}\n\
             Both copies of the vocabulary live at the repository root. The extension-less \
             one is not a build artefact and is not generated by anything: it is committed, \
             because it is what the namespace IRI resolves to."
        )
    })
}

#[test]
fn the_extension_less_copy_is_byte_identical_to_ns_ttl() {
    let ttl = read(NS_TTL);
    let bare = read(NS_BARE);

    assert!(
        ttl.len() > 1000,
        "{NS_TTL} is only {} bytes, which is not the vocabulary. Either it was truncated or \
         this test is reading the wrong file — and the comparison below would then be \
         confirming that two empty files agree.",
        ttl.len()
    );

    // Length first, and separately: "the files differ" plus two byte counts is
    // usually enough to say WHICH edit went missing, where a first-differing
    // offset in the middle of a comment block says almost nothing.
    assert_eq!(
        bare.len(),
        ttl.len(),
        "{NS_BARE} is {} bytes and {NS_TTL} is {}. They are one vocabulary published at two \
         paths: a reader who opens the file in this repository and a tool that dereferences \
         the namespace must not be reading different terms. Copy {NS_TTL} over {NS_BARE}.",
        bare.len(),
        ttl.len()
    );

    let first = bare
        .iter()
        .zip(ttl.iter())
        .position(|(a, b)| a != b)
        .map(|i| {
            let line = 1 + ttl[..i].iter().filter(|c| **c == b'\n').count();
            format!("first differing byte at offset {i}, {NS_TTL} line {line}")
        });
    assert!(
        first.is_none(),
        "{NS_BARE} and {NS_TTL} are the same length and different bytes ({}). Both parse, \
         both look right, and nothing anywhere would report that the namespace resolves to a \
         vocabulary the repository does not contain.",
        first.unwrap_or_default()
    );
}
